version: "3"
services:
  web:
    build: ./internship-client
    ports:
      - 4200:4200
  auth:
    build: ./internship-server/authentication-microservice
    ports:
      - 3001:3001
    environment:
      AUTH_HOST: auth
      USER_HOST: user
  internship:
    build: ./internship-server/internship-microservice
    ports:
      - 3003:3003
    environment:
      DB_HOST: mongo
      INTERNSHIP_HOST: internship
    links:
      - mongo
  user:
    build: ./internship-server/user-microservice
    environment:
      DB_HOST: mongo
      AUTH_HOST: auth
      USER_HOST: user
    links:
      - mongo
  mongo:
    image: mongo
    restart: always