version: "2"
services:
  web:
    build: ./youbrary-client
    ports:
      - 8085:4200
  auth:
    build: ./youbrary-server/authentication-microservice
    ports:
      - 3001:3001
    environment:
      AUTH_HOST: auth
      USER_HOST: user
  book:
    build: ./youbrary-server/book-microservice
    ports:
      - 3003:3003
    environment:
      DB_HOST: mongo
      BOOK_HOST: book
    links:
      - mongo
  user:
    build: ./youbrary-server/user-microservice
    environment:
      DB_HOST: mongo
      AUTH_HOST: auth
      USER_HOST: user
    links:
      - mongo
  mongo:
    image: mongo
    restart: always